module.exports = {
  menu: {
    sys_label: 'system info',
    sys_run: 'system run',
    sys_monitor: 'system monitor',
    sys_map: 'system map',
    home_video: 'video Page',
    graphicGather_label: 'Graphic Gathering',
    dataRecord_label: 'Inspection Record',
    robot_label: 'Robot Setting',
    hardware_config_label: 'Hardware Configuration',
    equip_config_label: 'Accessories settings',
    taskConfig_label: 'Task configuration',
    inspectPoints_config: 'Inspection point configuration',
    planTask_label: 'Inspection plan configuration',
    processTask_label: 'Task flow configuration',
    process_cofig_label: 'Process configuration',
    video_surveil_label: 'Video Surveillance',
    alarm_label: 'Alarm system',
    alarm_statics_label: 'Alarm statistics',
    equip_alarm_label: 'Inspection record',
    real_alarm_task: 'real task',
    real_alarm_label: 'Real-time alert',
    charge_config_label: 'Charging configuration',
    export_report_label: 'Report export',
    alarm_label: 'Alarm Setting',
    monitor: 'monitor',
    config: 'config',
    carrier_config: 'carrier config',
    mission_config: 'mission config',
    log_config: 'log config',
    feature: 'feature',
    control: 'control',
    feature_log: 'log',
    feature_traffic_control: 'traffic control',
    feature_path_plan: 'path plan',
    feature_dispatch: 'dispatch',
    statics: 'statics',
    agv_statics: 'AGV statics table',
    runtime_statics: 'runtime statics',
    fault_statics: 'fault statics',
    charge_statics: 'charge statics',
    system: 'system',
    system_language: 'language',
    system_user: 'User Management',
    map1: 'map',
    video_record_config_label: 'video recorder setting',
    system_setting: 'system setting',
    charging_strategy_label: 'charging strategy',
    charging_station_label: 'charging station',
  },
  login: {
    title: 'Inspection Robot Monitoring Platform',
    login: 'Login RightNow',
  },
  dashboard: {
    two_video_label: 'Image area 2',
    feature_label: 'Features',
    login_label: 'log in',
    one_video_label: 'Image area No. 1',
    video_control_label: 'Camera control area',
    enlarge_label: 'enlarge',
    shrink_label: 'Shrink',
    start_video_label: 'Start recording',
    end_video_label: 'End recording',
    photo_label: 'Take pictures',
    login_camera_label: 'Login camera',
    select_camera_label: 'Select camera:',
    inspect_map_label: 'Inspection map',
  },
  equip_setting: {
    equip_list_label: 'Accessories list',
    add_equip_label: 'Add accessories',
    equip_name: 'Accessory name:',
    equip_tooltip: 'Please enter the name of the accessory',
    inquire_label: 'Start query',
    plusAccesso_label: 'Add accessories',
    editAccesso_label: 'Modify',
    accesso_number: 'Numbering:',
    accesso_type: 'Types of:',
    accesso_brand: 'Brand:',
    accesso_state: 'status:',
    accesso_ip: 'IP: ',
    accesso_port: 'port: ',
    camera_type: 'Camera type:',
    brand_name: 'Brand name:',
    user_name: 'username:',
    password_label: 'password:',
    sure_label: 'Sure',
    cancel_label: 'cancel',
    deleteAccesso_label: 'Remove',
    accesso_details: 'Accessories details',
  },
  robot_setting: {
    robot_list: 'Robot list',
    robot_name: 'Robot name:',
    inquire_label: 'Start query',
    addRobot_label: 'Add robot',
    sure_label: 'Sure',
    cancel_label: 'Cancel',
    editRobot_label: 'Modify',
    editRobot_btn: 'edit',
    deleteRobot_label: 'Delete',
    setInspec_label: 'Configure inspection points',
    robot_tooltip: 'Please enter the robot name',
    pointMaintenance_label: 'Point table maintenance',
    taskMaintenance_label: 'Task maintenance',
    plusRobot_label: 'Add robot',
    robot_id_label: 'Robot ID:',
    robotNum_label: 'Robot code:',
    applySite_label: 'Application site:',
    robotName_label: 'Robot name:',
    robot_index_label: 'Robot serial number:',
    robotIP_label: 'Robot IP:',
    robotType_label: 'Robot type:',
    infraredCamera_label: 'Infrared camera:',
    selectedRobotTypes_label: 'Please select AGV type',
    ifBind_standby_label: 'Whether to bind the standby point:',
    bind_standby_label: 'Bind Standby',
    ifBind_simuCar_label: 'Whether to bind the simulation car:',
    bind_simuCar_label: 'Bind simulation car',
    accessory_operate_label: 'Related accessories',
    access_operate_label: 'Related accessory settings',
    robot_details_label: 'Robot details',
    accesso_type_label: 'Accessory type:',
    accesso_list_label: 'Accessories list:',
    accesso_feature_label: 'Accessory function:',
    add_related_label: 'Add association',
  },
  alarm_setting: {
    alarm_standard_settings: 'Alarm standard value setting',
    area_name: 'Area name:',
    area_tooltip: 'Please enter area name',
    inquire_label: 'Start query',
    addAlarm_label: 'Add zone alarm value',
    editAlarm_label: 'Modify area alarm value',
    deleteAlarm_label: 'Delete zone alarm value',
    detectPoint_lable: 'Monitoring points',
    intitAlarmState_lable: 'Alarm initial state',
    alarmLevel_lable: 'Alarm level',
    alarmID_lable: 'Alarm code',
    deviceName_lable: 'Equipment name',
    alarmDetailSet_btn: 'Set the upper and lower alarm limits',
    area_select: 'Please select the area name',
    detctPoint_select: 'Please select a monitoring point',
    device_select: 'Please select the initial state of the alarm',
    alarmID_select: 'Please select the alarm code',
  },
  inspection_setting: {
    inspecPoint_list: 'List of inspection points',
    inspecName_label: 'Name of inspection point:',
    inspec_tooltip: 'Please enter the name of the inspection point',
    inquire_label: 'Start query',
    addInspec_label: 'Add inspection point',
    editInspec_label: 'Modify inspection points',
    deleteInspec_label: 'Delete inspection point',
    inqireDetail_label: 'see details',
    config_label: 'Configuration',
    action_label: 'action',
    action_manage_label: 'Action management',
    edit_label: 'modify',
    delete_label: 'delete',
    inspectPoint_config_label: 'Inspection point configuration',
    current_inspect_name: 'Name of current inspection point:',
    sure_add_label: 'Sure',
    cancel_add_label: 'Cancel',
    plusInspect_label: 'New inspection point',
    editInspect_label: 'Modify inspection points',
  },
  process_config: {
    taskProcess_manage_label: 'Task flow management',
    addInspectTask_label: 'Add inspection process',
    editInspectTask_label: 'Modify the inspection process',
    deleteInspectTask_label: 'Delete inspection process',
    edit_label: 'modify',
    delete_label: 'delete',
    inspectTask_list: 'Inspection process list',
    config_label: 'Configuration',
    config_inspectTask: 'Configure inspection task points',
    current_robot_name: 'Current robot name:',
    current_inspect_name: 'Name of current inspection task:',
    taskInspect_point: 'Task inspection point',
    sure_add_label: 'Sure',
    cancel_add_label: 'Cancel',
    action_param_label: 'Action parameters',
    action_list: 'Action list',
  },
  plan_config: {
    robotTask_manage: 'Robot task management',
    addTimedTask_label: 'Add a scheduled task',
    editTimedTask_label: 'Modify timed tasks',
    deleteTimedTask_label: 'Delete scheduled tasks',
    timedTask_list: 'Scheduled task list',
    edit_label: 'modify',
    delete_label: 'delete',
    create_now_label: 'carried out',
    inqireDetail_label: 'see details',
    planTask_detail_label: 'Scheduled task details',
    sure_label: 'Confirm',
    cancel_label: 'Cancel',
  },
  charge_config: {
    charge_station_setting: 'Charging station settings',
    charge_model_config: 'Charging mode configuration',
    charge_model_setting: 'Charging mode setting',
    monitor_setting: 'Monitor settings',
    addCharge_station_label: 'Add charging station',
    edit_label: 'modify',
    delete_label: 'delete',
    plusCharge_station: 'Add charging station',
    editCharge_station: 'Modify charging station',
    sure_label: 'Confirm',
    cancel_label: 'Cancel',
    charge_model_label: 'Charging mode:',
    timeCharge_thresold_label: 'Timing charging threshold:',
    freeCharge_thresold_label: 'Idle charge threshold:',
    start_time_label: 'Starting time:',
    end_time_label: 'End Time:',
    remark_label: 'Remarks:',
    add_label: 'increase',
    lock_charge_station: 'Lock charging station',
    unlock_charge_station: 'unlock',
    select_agreement_type: 'Please select agreement type',
    extended_electrode_label: 'Extended electrode',
    retract_electrode_label: 'Retract electrode',
  },
  inspect_record: {
    equip_alarm_statics: 'Inspection data statistics',
    export_label: 'Export',
    export_alarm_data: 'Export alarm data',
    file_name: 'file name:',
    text_type: 'Text type:',
    will_export: 'Export',
    cancel_label: 'Cancel',
    equipAlarm_detail_label: 'Inspection data details',
    filter_condition_label: 'Filter conditions:',
    real_alarm_list: 'Real-time alarm list',
  },
  system: {
    switch_language: 'switch language',
    Simplified_Chinese: 'Simplified Chinese',
    English: 'English',
  },
  monitordata: {
    AGVID: 'Number:',
    ip: 'Ip:',
    type: 'Type:',
    status: 'Status:',
    battery_level: 'Battery:',
    software_version: 'SW Ver:',
    Number_of_tasks: 'Number of tasks waiting',
    detail: 'detail',
    Running: 'Running',
    task_complete: 'Completed Tasks',
    charge_count: 'Charge Times',
    online_total: 'Online Duration',
    task_free: 'Free',
    task_dispatching: 'Dispatching',
    task_operation: 'Operating',
    task_completed: 'Completed',
    task_idle: 'Free',
    task_error: 'Error',
  },
  user: {
    Add_user: 'Add user',
    UserName: 'UserName',
    Email: 'Email',
    Role: 'Role',
    Registration_time: 'Registration time',
    Last_login_time: 'Last login time',
    operate: 'operate',
    password: 'password',
    Please_enter_your_password: 'Please enter your password',
    Confirm: 'Confirm',
    Cancel: 'Cancel',
    Edit: 'Edit',
    Delete: 'Delete',
    Tourist: 'Tourist',
    Geust: 'Geust',
    Administrator: 'Administrator',
    Success: 'Success',
    Delete_Success: 'Delete Success',
    Failure: 'Failure',
    Delete_Failure: 'Delete Failure',
    Update_Success: 'Update Success',
    Update_Failure: 'Update Failure',
    Create_Success: 'Create Success',
    Create_Failure: 'Create Failure',
    interface_call_failed_tip: 'Interface call failed',
  },
  map_config: {
    agv_list_label: 'AGV List',
    agv_state_label: 'AGV State',
    agv_planned_route: 'Show Planned Route',
    task_status: 'Task Status:',
    battery_level: 'Battery:',
    agv_blocked_state: 'Blocked State:',
    agv_connection_status: 'Connection Status:',
    agv_number: 'Numbers of AGV:',
    agv_types: 'Types of AGV:',
    x_coordinate: 'X coordinate:',
    y_coordinate: 'Y coordinate:',
    plan_start_point: 'Planning starting point:',
    plan_end_point: 'Planning the end:',
    agv_behavior_code: 'Behavior code:',
    regulate_type: 'Type of regulation:',
    regulate_param: 'Regulatory parameters:',
    agv_control_mode: 'Control mode:',
    agv_obstacle: 'Obstacle:',
    agv_emergency_stop: 'Emergency stop:',
    task_perform_success_tip: 'The task was successfully issued',
    task_perform_fail_tip: 'Task delivery failed',
  },
  agv_statics: {
    kanban_home_label: 'Kanban Home',
    start_time_label: 'Starting Time：',
    end_time_label: 'End Time：',
    query_label: 'Inquire',
    idle_ratio_label: 'Idle Ratio(%)',
    charge_ratio_label: 'Charge Ratio(%)',
    agv_efficy_label: 'AGV Efficiency(%)',
    failure_ratio_label: 'Failure Ratio(%)',
    choose_date_time_tip: 'Choose date and time',
    agv_idle_detail_label: 'Car idle data details',
    agv_charge_detail_label: 'Car charging data details',
    agv: 'Car',
    agv_location: 'Position',
    export_label: 'Export',
  },
  home_page: {
    system_run_msg: 'system operation information',
    current_alarm: 'real time alarm',
    equipment_status: 'equipment status',
    monitor_information: 'system monitoring information',
    ptz_control: 'PTZ control',
  },
};
