module.exports = {
  menu: {
    sys_label: '系统信息',
    sys_run: '系统运行',
    sys_monitor: '系统监控',
    sys_map: '地图监控',
    graphicGather_label: '图像采集',
    dataRecord_label: '数据记录',
    robot_label: '机器人配置',
    hardware_config_label: '硬件配置',
    area_config_label: '区域配置',
    equip_config_label: '配件配置',
    taskConfig_label: '巡检配置',
    inspectPoints_config: '巡检点配置',
    planTask_label: '巡检计划配置',
    processTask_label: '巡检流程配置',
    process_cofig_label: '流程配置',
    video_surveil_label: '视频监控',
    alarm_label: '告警配置',
    alarm_statics_label: '告警统计',
    equip_alarm_label: '巡检记录',
    real_alarm_task: '实时任务',
    real_alarm_label: '实时告警',
    history_alarm_label: '历史告警',
    charge_config_label: '充电配置',
    export_report_label: '报表导出',
    monitor: '监控',
    config: '配置',
    carrier_config: '小车配置',
    mission_config: '任务配置',
    log_config: '日志配置',
    feature: '功能',
    control: '控制',
    feature_log: '日志记录',
    feature_traffic_control: '交通管制',
    feature_path_plan: '路径规划',
    feature_dispatch: '车辆调度',
    statics: '统计',
    agv_statics: 'AGV统计列表',
    runtime_statics: '运行统计',
    fault_statics: '故障统计',
    charge_statics: '充电统计',
    system: '系统',
    system_language: '语言',
    system_user: '用户管理',
    map1: '地图',
    system: '系统管理',
    sys_u_mg: '用户管理',
    sys_role_mg: '角色管理',
    sys_purview_mg: '权限管理',
    video_record_config_label: '硬盘录像机配置',
    system_setting: '授权管理',
    charging_strategy_label: '充电策略配置',
    charging_station_label: '充电站配置',
  },
  login: {
    title: '巡检机器人监控平台',
    login: '登录',
  },
  dashboard: {
    two_video_label: '二号影像区',
    feature_label: '功 能',
    login_label: '登 录',
    one_video_label: '影像区',
    video_control_label: '摄像头控制区',
    enlarge_label: '放大',
    shrink_label: '缩小',
    start_video_label: '开始录像',
    end_video_label: '结束录像',
    photo_label: '拍照',
    login_camera_label: '登录摄像头',
    select_camera_label: '选择摄像头:',
    inspect_map_label: '巡检地图',
  },
  public_vary: {
    query_label: '查询',
    dealWith_label: '处理',
    details_label: '详情',
    warning_tip: '提示',
    sure_label: '确 定',
    cancel_label: '取 消',
    delete_operate_tip: '此操作将永久删除该数据, 是否继续?',
    cancel_label: '取 消',
    append_succeed_label: '新增成功',
    succeed_succeed_label: '修改成功',
    delete_succeed_label: '删除成功',
  },
  comment_vary: {
    start_time_label: '开始时间',
    end_time_label: '结束时间',
    start_time: '开始时间：',
    end_time: '结束时间：',
    default_time_label: '起止时间：',
    query_label: '查 询',
    inquire_failed_label: '查询失败',
    inquire_failed_tip: '所选开始时间晚于结束时间',
  },
  alarm_dealWith: {
    alarm_code_label: '告警码',
    alarm_name_label: '告警名称',
    alarm_status_label: '告警状态',
    maxAlarm_level_label: '最大告警级别',
    maxAlarm_value_label: '最大告警数值',
    machine_name_label: '机器名称',
    equipment_name_label: '设备名称',
    happen_time: '发生时间',
    dealWith_time: '处理时间',
    alarm_details_label: '告警详情',
    alarm_dealWith_label: '告警处理',
    alarm_info_label: '告警信息',
    inspection_info_label: '巡检信息',
    dealWith_people_label: '处理人',
    dealWith_way_label: '处理方式',
    dealWith_results_label: '处理结果',
    dealWith_describe_label: '处理描述',
  },
  area_setting: {
    area_code_label: '区域编码',
    area_name_label: '区域名称',
    bigArea_name_label: '父区域',
    add_area_label: '新增区域',
    editor_area_label: '编辑区域',
    keyword_label: '关键字查询',
    input_keyword_label: '请输入关键字',
  },
  equip_setting: {
    equip_list_label: '配件列表',
    add_equip_label: '新增配件',
    equip_name: '配件名称',
    equip_tooltip: '请输入配件名称',
    inquire_label: '查询',
    plusAccesso_label: '新增配件',
    editAccesso_label: '修改配件',
    accesso_number: '配件编号',
    accesso_type: '配件类型',
    accesso_brand: '配件品牌',
    accesso_state: '配件状态',
    accesso_ip: 'IP',
    accesso_port: '端口',
    camera_type: '设备类型',
    brand_name: '配件品牌',
    user_name: '用户名',
    password_label: '密码',
    sure_label: '确 定',
    cancel_label: '取 消',
    deleteAccesso_label: '删 除',
    accesso_details: '配件详情',
  },
  robot_setting: {
    robot_list: '机器人列表',
    robot_name: '机器人名称',
    inquire_label: '查询',
    addRobot_label: '新增机器人',
    cancel_label: '取 消',
    sure_label: '确 定',
    editRobot_label: '修改机器人',
    editRobot_btn: '修改',
    deleteRobot_label: '删 除',
    setInspec_label: '配置巡检点',
    robot_tooltip: '请输入关键字',
    pointMaintenance_label: '点表维护',
    taskMaintenance_label: '任务维护',
    plusRobot_label: '新增机器人',
    area_label: '区域',
    robot_id_label: '机器人ID',
    robotNum_label: '机器人编码',
    applySite_label: '应用场地：',
    robotName_label: '机器人名称',
    robot_index_label: '机器人序号',
    robotIP_label: '机器人IP',
    robotType_label: '机器人类型',
    infraredCamera_label: '红外摄像头',
    selectedRobotTypes_label: '请选择AGV类型',
    ifBind_standby_label: '是否绑定待命点',
    bind_standby_label: '绑定待命点',
    ifBind_simuCar_label: '是否绑定模拟车',
    bind_simuCar_label: '绑定模拟车',
    accessory_operate_label: '关联配件',
    access_operate_label: '关联配件设置',
    robot_details_label: '机器人详情',
    accesso_type_label: '配件类型',
    accesso_list_label: '配件列表',
    accesso_feature_label: '配件功能',
    add_related_label: '添加关联',
  },
  alarm_setting: {
    alarm_standard_settings: '报警标准值设置',
    area_name: '区域名称：',
    area_tooltip: '请输入区域名称',
    inquire_label: '查询',
    add_label: '添加',
    addAlarm_label: '添加告警',
    editAlarm_label: '修改告警',
    deleteAlarm_label: '删除区域报警值',
    detectPoint_lable: '监测点',
    intitAlarmState_lable: '报警初始状态',
    alarmLevel_label: '告警级别',
    alarmID_label: '告警码',
    alarm_name_label: '告警名称',
    alarm_type_label: '告警类型',
    equipment_type_label: '设备类型',
    alarm_area_label: '告警区域',
    alarm_produce_label: '告警产生门限',
    alarm_repair_label: '告警修复门限',
    alarm_area_label: '报警区域',
    deviceName_lable: '设备ID',
    alarmDetailSet_btn: '设置报警上下限值',
    area_select: '请选择区域名称',
    detctPoint_select: '请选择监测点',
    device_select: '请选择报警初始状态',
    alarmID_select: '请选择报警码',
    correlation_operate_label: '详情配置',
    process_mode_label: '处理方式',
    upper_limit_label: '上限值',
    lower_limit_label: '下限值',
  },
  inspection_setting: {
    inspecPoint_list: '巡检点列表',
    inspecName_label: '巡检点名称：',
    inspec_tooltip: '请输入巡检点名称',
    inquire_label: '查询',
    addInspec_label: '新增巡检点',
    editInspec_label: '修改巡检点',
    deleteInspec_label: '删除巡检点',
    inqireDetail_label: '详 情',
    config_label: '配置',
    action_label: '动作',
    action_manage_label: '动作管理',
    edit_label: '修改',
    delete_label: '删除',
    inspectPoint_config_label: '巡检点配置',
    current_inspect_name: '当前巡检点名称：',
    sure_add_label: '确 定',
    cancel_add_label: '取 消',
    plusInspect_label: '新增巡检点',
    editInspect_label: '修改巡检点',
    plus_video_label: '新增录像',
    edit_video_label: '修改录像',
  },
  process_config: {
    taskProcess_manage_label: '任务流程管理',
    addInspectTask_label: '添加巡检流程',
    editInspectTask_label: '修改巡检流程',
    deleteInspectTask_label: '删除巡检流程',
    edit_label: '修改',
    delete_label: '删除',
    inspectTask_list: '巡检流程列表',
    config_label: '配置',
    config_inspectTask: '配置巡检任务点',
    current_robot_name: '当前机器人名称：',
    current_inspect_name: '当前巡检任务名称：',
    taskInspect_point: '任务巡检点',
    sure_add_label: '确 定',
    cancel_add_label: '取 消',
    action_param_label: '动作参数',
    action_list: '动作列表',
  },
  plan_config: {
    robotTask_manage: '机器人任务管理',
    addTimedTask_label: '添加巡检计划',
    editTimedTask_label: '修改巡检计划',
    deleteTimedTask_label: '删除巡检计划',
    timedTask_list: '巡检计划列表',
    edit_label: '修改',
    delete_label: '删除',
    create_now_label: '执行',
    inqireDetail_label: '详 情',
    planTask_detail_label: '巡检计划详情',
    sure_label: '确 定',
    cancel_label: '取 消',
  },
  charge_config: {
    charge_station_setting: '充电站设置',
    charge_model_config: '充电模式配置',
    charge_model_setting: '充电模式设置',
    monitor_setting: '监听设置',
    addCharge_station_label: '添加充电站',
    edit_label: '修改',
    delete_label: '删除',
    plusCharge_station: '添加充电站',
    editCharge_station: '修改充电站',
    sure_label: '确 定',
    cancel_label: '取 消',
    charge_model_label: '充电模式：',
    timeCharge_thresold_label: '定时充电阈值：',
    freeCharge_thresold_label: '闲置充电阈值：',
    start_time_label: '开始时间：',
    end_time_label: '结束时间：',
    remark_label: '备注：',
    add_label: '增 加',
    lock_charge_station: '锁定充电站',
    unlock_charge_station: '解除锁定',
    select_agreement_type: '请选择协议类型',
    extended_electrode_label: '伸出电极',
    retract_electrode_label: '缩回电极',
  },
  inspect_record: {
    equip_alarm_statics: '巡检数据统计',
    export_label: '导 出',
    export_alarm_data: '导出告警数据',
    file_name: '文件名：',
    text_type: '文本类型：',
    will_export: '导 出',
    cancel_label: '取 消',
    equipAlarm_detail_label: '巡检数据详情',
    filter_condition_label: '过滤条件：',
    real_alarm_list: '实时告警列表',
  },
  system: {
    switch_language: '切换语言',
    Simplified_Chinese: '简体中文',
    English: '英语',
  },
  monitordata: {
    AGVID: '编号:',
    ip: 'ip:',
    type: '类型:',
    status: '状态:',
    battery_level: '电量:',
    software_version: '版本:',
    Number_of_tasks: '待执行任务数',
    detail: '详细',
    Running: '运行中',
    task_complete: '已完成任务',
    charge_count: '充电次数',
    online_total: '在线时长',
    panelcard_detail: '详细',
    task_free: '空闲',
    task_dispatching: '运行中',
    task_operation: '操作',
    task_completed: '已完成',
    task_idle: '空闲',
    task_error: '错误',
  },
  user: {
    Add_user: '添加用户',
    UserName: '用户名',
    Email: '邮箱',
    Role: '角色',
    Registration_time: '注册时间',
    Last_login_time: '最后一次登录时间',
    operate: '操作',
    password: '密码',
    Please_enter_your_password: '请输入密码',
    Confirm: '确 定',
    Cancel: '取 消',
    Edit: '编辑',
    Delete: '删除',
    Tourist: '游客',
    Geust: '普通用户',
    Administrator: '管理员',
    Success: '成功',
    Delete_Success: '删除成功',
    Failure: '失败',
    Delete_Failure: '删除失败',
    Update_Success: '更新成功',
    Update_Failure: '更新失败',
    Create_Success: '创建成功',
    Create_Failure: '创建失败',
    Save_Failure: '保存失败',
    interface_call_failed_tip: '接口调用失败',
  },
  map_config: {
    agv_list_label: 'AGV列表',
    agv_state_label: 'AGV状态',
    agv_planned_route: '显示规划路线',
    task_status: '任务状态:',
    battery_level: '电量:',
    agv_blocked_state: '阻塞状态:',
    agv_connection_status: '连接状态:',
    agv_number: 'AGV编号:',
    agv_types: 'AGV类型:',
    x_coordinate: 'X坐标:',
    y_coordinate: 'Y坐标:',
    plan_start_point: '规划起点:',
    plan_end_point: '规划终点:',
    agv_behavior_code: '行为码:',
    regulate_type: '管制类型:',
    regulate_param: '管制参数:',
    agv_control_mode: '控制模式:',
    agv_obstacle: '障碍物:',
    agv_emergency_stop: '急停:',
    task_perform_success_tip: '任务下发成功',
    task_perform_fail_tip: '任务下发失败',
  },
  agv_statics: {
    kanban_home_label: '看板主界面',
    start_time_label: '开始时间：',
    end_time_label: '结束时间：',
    query_label: '查询',
    idle_ratio_label: '空闲占比(%)',
    charge_ratio_label: '充电占比(%)',
    agv_efficy_label: 'AGV效率(%)',
    failure_ratio_label: '故障率(%)',
    choose_date_time_tip: '选择日期时间',
    agv_idle_detail_label: '小车空闲数据明细',
    agv_charge_detail_label: '小车充电数据明细',
    agv: '小车',
    agv_location: '位 置',
    export_label: '导 出',
  },
  home_page: {
    system_run_msg: '系统运行信息',
    current_alarm: '实时报警信息',
    equipment_status: '设备状态',
    monitor_information: '系统监控信息',
    ptz_control: '云台控制',
  },
};
